server:
  #port: 8081
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: ms-catalogo-service

  datasource:
    url: jdbc:mysql://localhost:3306/ms_catalogo
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  #datasource:
  #  url: jdbc:h2:mem:ms_catalogo
  #  driver-class-name: org.h2.Driver
  #  username: sa
  #  password: password

  #jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false # Deshabilita la consola de H2
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
